require('plugins')
require('plugin-configs/comment')
require('plugin-configs/diagnostics')
require('plugin-configs/lsp')
require('plugin-configs/telescope')
require('plugin-configs/treesitter')
require('plugin-configs/vim-line')
require('plugin-configs/diffview')
require('plugin-configs/compe')
require('plugin-configs/custom-remaps')
require('plugin-configs/null-ls')
require('global-configs')

